### ISSUE TITLE
Convert High Level Overview Lesson Plan

### ISSUE THREAD

**Issue by jsmcintyre25** [wptrainingteam/high-level-overview#1]
Convert Lesson Plan to GitHub

- [x]  copy and paste from Make site
- [ ]  clean up the Markdown
- [ ]  download the old images
- [ ]  upload the images into GitHub
- [ ]  swap out the image links

**Comment by JulieKuehl** [comment]
https://make.wordpress.org/training/handbook/user-lessons/high-level-overview/
